from ProductRegisters.FeedbackFunctions.FeedbackFunction import FeedbackFunction
from ProductRegisters.FeedbackFunctions.MPR import MPR
from ProductRegisters.FeedbackFunctions.CMPR import CMPR
from ProductRegisters.FeedbackFunctions.Fibonacci import Fibonacci
from ProductRegisters.FeedbackFunctions.Galois import Galois
from ProductRegisters.FeedbackFunctions.CrossJoin import CrossJoin
from ProductRegisters.FeedbackFunctions.TFunction import TFunction
from ProductRegisters.FeedbackFunctions.FCSR import FCSR